### PR TITLE
Mergy2

### PR DESCRIPTION
**Pull request by carols10cents**
This is a merge in of upstream changes that includes the use of a worker pool with a timeout!!

/cc @BobTheBotMaker what do you want to do with this before we merge/deploy? Perf test?

### CODE REVIEW

**Comment by srobbibaro** [comment]
@ninjapanzer - I assume we're just going to look over Carol's last three commits on this PR.

**Comment by srobbibaro** [comment]
Works for me! Over to @ninjapanzer to sign off on. However, I'd like to wait to hear back from @BobTheBotMaker too.

**Comment by ninjapanzer** [comment]
very cool. lets deploy this so we can perf test it

**Comment by BobTheBotMaker** [comment]
Its been deployed to http://54.162.41.210/ I need to work with @jkoenig311 to setup / revive the load test that we used in the past.

**Pull request merged**
